const assert=require('node:assert/strict');const {before,after,test}=require('node:test');require('../src/config/bootstrapEnv');process.env.NODE_ENV='test';const db=process.env.TEST_DB_NAME||`${process.env.DB_NAME}_test`;process.env.DB_NAME=db;const {migrate}=require('../src/migrations/run');const {initializeDatabase,getSequelize}=require('../src/config/db');const {getModels}=require('../src/models');const {summary,summaryByExperiment}=require('../src/services/matchRecommendationMetricsService');let m,ids=[];
async function user(name){const u=await m.User.create({name,email:`attr-${crypto.randomUUID()}@test.local`,phoneNumber:'',authProvider:'local'});ids.push(u.id);return u;}
async function impression(viewer,candidate,experimentId,variant,score=80,coverage=70){return m.MatchRecommendationEvent.create({viewerUserId:viewer.id,candidateUserId:candidate.id,eventType:'impression',rankingVersion:'v2',requestId:crypto.randomUUID(),page:1,position:1,score,coverage,experimentId,variant});}
const crypto=require('crypto');
assert.doesNotHaveOwn=(object,key)=>assert.equal(Object.hasOwn(object,key),false);
before(async()=>{await migrate({databaseName:db,quiet:true});await initializeDatabase();m=getModels();});
after(async()=>{if(m&&ids.length){await m.MatchRecommendationEvent.destroy({where:{viewerUserId:ids}});await m.DiscoverAction.destroy({where:{actorUserId:ids}});await m.RoseTransaction.destroy({where:{senderId:ids}});await m.Match.destroy({where:{userOneId:ids}});await m.User.destroy({where:{id:ids}});}await getSequelize().close();});
test('persisted experiment grouping and authoritative outcome attribution are isolated and idempotent',async()=>{const [a,b,c,d,e]=await Promise.all(['A','B','C','D','E'].map(user));await impression(a,b,'experiment-a','control',20,20);await impression(c,d,'experiment-a','variant',90,90);await impression(a,c,'experiment-b','control',60,50);await impression(a,b,'experiment-a','control',20,20);await m.DiscoverAction.upsert({actorUserId:a.id,targetUserId:b.id,action:'like'});await m.DiscoverAction.upsert({actorUserId:c.id,targetUserId:d.id,action:'superLike'});await m.RoseTransaction.create({senderId:a.id,recipientId:b.id,idempotencyKey:crypto.randomUUID(),status:'sent'});await m.Match.create({userOneId:Math.min(c.id,d.id),userTwoId:Math.max(c.id,d.id)});await m.DiscoverAction.upsert({actorUserId:e.id,targetUserId:b.id,action:'like'});await m.DiscoverAction.upsert({actorUserId:a.id,targetUserId:e.id,action:'like'});
const groups=await summaryByExperiment();const control=groups.find(x=>x.experimentId==='experiment-a'&&x.variant==='control').metrics,variant=groups.find(x=>x.experimentId==='experiment-a'&&x.variant==='variant').metrics,other=groups.find(x=>x.experimentId==='experiment-b').metrics;assert.equal(control.impressions,2);assert.equal(control.observedLikes,1);assert.equal(control.observedSuperLikes,0);assert.equal(control.observedRoses,1);assert.equal(control.observedMatches,0);assert.equal(variant.impressions,1);assert.equal(variant.observedLikes,0);assert.equal(variant.observedSuperLikes,1);assert.equal(variant.observedMatches,1);assert.equal(other.impressions,1);assert.equal(other.observedLikes,0);assert.equal(control.scoreBands.find(x=>x.key==='0_20').observedLikes,1);assert.equal(variant.coverageBuckets.find(x=>x.key==='high').observedMatches,1);assert.deepEqual(await summaryByExperiment(),groups);const raw=await summary({experimentId:'experiment-a',variant:'control'});assert.equal(raw.uniqueCandidates,1);assert.doesNotHaveOwn(raw,'email');assert.doesNotHaveOwn(raw,'profiles');});

test('repeated impressions attribute Super Like, Rose, and Match only once',async()=>{const [a,b,c,d,e,f]=await Promise.all(['SA','SB','RA','RB','MA','MB'].map(user));for(const [v,t,id,variant,score,coverage] of [[a,b,'repeat-super','control',70,70],[a,b,'repeat-super','control',70,70],[c,d,'repeat-rose','control',70,70],[c,d,'repeat-rose','control',70,70],[e,f,'repeat-match','control',20,20],[e,f,'repeat-match','variant',90,90]])await impression(v,t,id,variant,score,coverage);await m.DiscoverAction.upsert({actorUserId:a.id,targetUserId:b.id,action:'superLike'});await m.RoseTransaction.create({senderId:c.id,recipientId:d.id,idempotencyKey:crypto.randomUUID(),status:'sent'});await m.Match.create({userOneId:Math.min(e.id,f.id),userTwoId:Math.max(e.id,f.id)});const groups=await summaryByExperiment();const superGroup=groups.find(x=>x.experimentId==='repeat-super').metrics,roseGroup=groups.find(x=>x.experimentId==='repeat-rose').metrics,controlMatch=groups.find(x=>x.experimentId==='repeat-match'&&x.variant==='control').metrics,variantMatch=groups.find(x=>x.experimentId==='repeat-match'&&x.variant==='variant').metrics;assert.equal(superGroup.impressions,2);assert.equal(superGroup.observedSuperLikes,1);assert.equal(roseGroup.impressions,2);assert.equal(roseGroup.observedRoses,1);assert.equal(controlMatch.observedMatches,0);assert.equal(variantMatch.observedMatches,1);assert.equal(variantMatch.scoreBands.find(x=>x.key==='81_100').observedMatches,1);assert.deepEqual(await summaryByExperiment(),groups);});

test('globally attributes outcomes once to the latest qualifying experiment context',async()=>{const users=await Promise.all(['A1','B1','A2','B2','A3','B3','A4','B4','A5','B5','A6','B6'].map(user));const at=n=>new Date(1700000000000+n*1000);const event=async(v,t,experimentId,variant,n,score=80,coverage=70)=>m.MatchRecommendationEvent.create({viewerUserId:v.id,candidateUserId:t.id,eventType:'impression',rankingVersion:'v2',requestId:crypto.randomUUID(),page:1,position:1,score,coverage,experimentId,variant,createdAt:at(n),updatedAt:at(n)});const action=async(v,t,type,n)=>m.DiscoverAction.create({actorUserId:v.id,targetUserId:t.id,action:type,createdAt:at(n),updatedAt:at(n)});const match=async(v,t,n)=>m.Match.create({userOneId:Math.min(v.id,t.id),userTwoId:Math.max(v.id,t.id),matchedAt:at(n)});
const [a,b,c,d,e,f,g,h,i,j,k,l]=users;
// Control then variant: the Match belongs only to the later variant context.
await event(a,b,'cross-match','control',1,35,25);await event(a,b,'cross-match','variant',2,85,90);await match(a,b,3);
// Reverse chronology proves attribution is temporal, rather than treatment-preferred.
await event(c,d,'reverse-match','variant',4);await event(c,d,'reverse-match','control',5);await match(c,d,6);
// A single Like before a later variant remains credited to the earlier control event.
await event(e,f,'before-later','control',7);await action(e,f,'like',8);await event(e,f,'before-later','variant',9);
// A Like that precedes every recommendation event has no recommendation attribution.
await action(g,h,'like',10);await event(g,h,'no-prior','control',11);
// Different experiment identifiers must not consume the same Match.
await event(i,j,'cross-experiment-a','variant',12);await event(i,j,'cross-experiment-b','control',13);await match(i,j,14);
// Cross-context Like validates the common directed action path.
await event(k,l,'cross-like','control',15);await event(k,l,'cross-like','variant',16);await action(k,l,'like',17);
const all=await summary();assert.equal(all.observedMatches>=3,true);assert.equal(all.observedLikes>=2,true);
const groups=await summaryByExperiment();const metrics=(id,variant)=>groups.find(group=>group.experimentId===id&&group.variant===variant).metrics;
const crossControl=metrics('cross-match','control'),crossVariant=metrics('cross-match','variant');assert.equal(crossControl.impressions,1);assert.equal(crossVariant.impressions,1);assert.equal(crossControl.observedMatches,0);assert.equal(crossVariant.observedMatches,1);assert.equal(crossControl.scoreBands.find(band=>band.key==='21_40').observedMatches,0);assert.equal(crossVariant.scoreBands.find(band=>band.key==='81_100').observedMatches,1);assert.equal(crossControl.coverageBuckets.find(bucket=>bucket.key==='low').observedMatches,0);assert.equal(crossVariant.coverageBuckets.find(bucket=>bucket.key==='high').observedMatches,1);
assert.equal(metrics('reverse-match','variant').observedMatches,0);assert.equal(metrics('reverse-match','control').observedMatches,1);assert.equal(metrics('cross-experiment-a','variant').observedMatches,0);assert.equal(metrics('cross-experiment-b','control').observedMatches,1);assert.equal(metrics('cross-like','control').observedLikes,0);assert.equal(metrics('cross-like','variant').observedLikes,1);assert.equal(metrics('before-later','control').observedLikes,1);assert.equal(metrics('before-later','variant').observedLikes,0);assert.equal(metrics('no-prior','control').observedLikes,0);assert.deepEqual(await summaryByExperiment(),groups);});
