name: amora_ai
description: "Premium AI-powered dating and matchmaking platform for India."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profiles/female/
    - assets/images/profiles/male/
    - assets/images/events/
    - assets/images/profiles/profile_gallery/
