name: amora_ai
description: "Premium AI-powered dating and matchmaking platform for India."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  cupertino_icons: ^1.0.8
  emoji_picker_flutter: ^4.5.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.2
  http: ^1.2.2
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  razorpay_flutter: ^1.4.5
  share_plus: ^12.0.2
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/branding/
    - assets/images/
    - assets/images/profiles/female/
    - assets/images/profiles/male/
    - assets/images/events/
    - assets/images/profiles/profile_gallery/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/amora_launcher_icon.png
  adaptive_icon_background: "#FFFBFD"
  adaptive_icon_foreground: assets/branding/amora_icon.png
  adaptive_icon_foreground_inset: 18
  remove_alpha_ios: true
  background_color_ios: "#FFFBFD"
  web:
    generate: true
    image_path: assets/branding/amora_launcher_icon.png
    background_color: "#FFFBFD"
    theme_color: "#FFFBFD"
  windows:
    generate: true
    image_path: assets/branding/amora_launcher_icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/branding/amora_launcher_icon.png
