const { DataTypes } = require('sequelize');

module.exports = (sequelize) => sequelize.define('Administrator', {
  id: { type: DataTypes.BIGINT.UNSIGNED, autoIncrement: true, primaryKey: true },
  name: { type: DataTypes.STRING(120), allowNull: false },
  email: { type: DataTypes.STRING(191), allowNull: false, unique: true, validate: { isEmail: true } },
  passwordHash: { type: DataTypes.STRING(255), allowNull: true },
  status: { type: DataTypes.ENUM('active', 'suspended', 'disabled'), allowNull: false, defaultValue: 'active' },
  version: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 1 },
  locale: { type: DataTypes.STRING(20), allowNull: false, defaultValue: 'en-IN' },
  timezone: { type: DataTypes.STRING(80), allowNull: false, defaultValue: 'Asia/Kolkata' },
  invitationStatus: { type: DataTypes.ENUM('not_required', 'pending', 'accepted', 'expired', 'revoked'), allowNull: false, defaultValue: 'not_required' },
  tokenVersion: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
  failedLoginAttempts: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
  lockedUntil: { type: DataTypes.DATE, allowNull: true },
  lastLoginAt: { type: DataTypes.DATE, allowNull: true },
  lastActiveAt: { type: DataTypes.DATE, allowNull: true },
  activatedAt: { type: DataTypes.DATE, allowNull: true },
  suspendedAt: { type: DataTypes.DATE, allowNull: true },
  suspendedByAdministratorId: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
  suspensionReasonCode: { type: DataTypes.STRING(40), allowNull: true },
  suspensionReasonDetail: { type: DataTypes.STRING(500), allowNull: true },
  suspensionEndsAt: { type: DataTypes.DATE, allowNull: true },
  createdByAdministratorId: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
}, { tableName: 'Administrators' });
