const { DataTypes } = require('sequelize');

module.exports = (sequelize) => sequelize.define('Event', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  title: { type: DataTypes.STRING(160), allowNull: false },
  description: { type: DataTypes.TEXT, allowNull: false },
  category: { type: DataTypes.STRING(80), allowNull: false },
  city: { type: DataTypes.STRING(100), allowNull: false },
  venueName: { type: DataTypes.STRING(160), allowNull: false },
  address: { type: DataTypes.STRING(255), allowNull: true },
  latitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
  longitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
  startDateTime: { type: DataTypes.DATE, allowNull: false },
  endDateTime: { type: DataTypes.DATE, allowNull: false },
  capacity: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
  waitlistCapacity: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
  status: { type: DataTypes.ENUM('draft', 'published', 'cancelled', 'completed'), allowNull: false, defaultValue: 'draft' },
  visibility: { type: DataTypes.ENUM('public', 'private'), allowNull: false, defaultValue: 'public' },
  registrationOpen: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },
  waitlistEnabled: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },
  heroImageUrl: { type: DataTypes.STRING(500), allowNull: true },
  organizerId: { type: DataTypes.INTEGER, allowNull: false },
  price: { type: DataTypes.DECIMAL(10, 2), allowNull: false, defaultValue: 0 },
  dressCode: { type: DataTypes.STRING(120), allowNull: true },
  minAge: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  maxAge: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  language: { type: DataTypes.STRING(160), allowNull: true },
  agenda: { type: DataTypes.JSON, allowNull: true },
  facilities: { type: DataTypes.JSON, allowNull: true },
  interests: { type: DataTypes.JSON, allowNull: true },
}, { tableName: 'Events' });
