const defineUser = require('./User'); const defineOtpToken = require('./OtpToken'); const defineRefreshToken = require('./RefreshToken'); const defineOnboardingProfile = require('./OnboardingProfile'); const defineDiscoverAction = require('./DiscoverAction'); const defineMatch = require('./Match'); const defineBoost = require('./Boost'); const defineDiscoverFilterPreference = require('./DiscoverFilterPreference'); const defineBlock = require('./Block'); const defineReport = require('./Report'); const defineReportEvidence = require('./ReportEvidence'); const defineConversation = require('./Conversation'); const defineConversationParticipant = require('./ConversationParticipant'); const defineMessage = require('./Message'); const defineMessageMedia = require('./MessageMedia'); const defineEvent = require('./Event'); const defineEventRegistration = require('./EventRegistration'); const defineEventWaitlist = require('./EventWaitlist'); const defineEventFeedback = require('./EventFeedback'); const defineEventCheckIn = require('./EventCheckIn'); const defineEventGroupMessage = require('./EventGroupMessage');
let models = {};
function initModels(sequelize) {
  if (models.User) return models;
  const User = defineUser(sequelize); const OtpToken = defineOtpToken(sequelize); const RefreshToken = defineRefreshToken(sequelize); const OnboardingProfile = defineOnboardingProfile(sequelize); const DiscoverAction = defineDiscoverAction(sequelize); const Match = defineMatch(sequelize); const Boost = defineBoost(sequelize); const DiscoverFilterPreference = defineDiscoverFilterPreference(sequelize); const Block = defineBlock(sequelize); const Report = defineReport(sequelize); const ReportEvidence = defineReportEvidence(sequelize); const Conversation = defineConversation(sequelize); const ConversationParticipant = defineConversationParticipant(sequelize); const Message = defineMessage(sequelize); const MessageMedia = defineMessageMedia(sequelize); const Event = defineEvent(sequelize); const EventRegistration = defineEventRegistration(sequelize); const EventWaitlist = defineEventWaitlist(sequelize); const EventFeedback = defineEventFeedback(sequelize); const EventCheckIn = defineEventCheckIn(sequelize); const EventGroupMessage = defineEventGroupMessage(sequelize);
  User.hasMany(RefreshToken, { foreignKey: 'userId', onDelete: 'CASCADE' }); RefreshToken.belongsTo(User, { foreignKey: 'userId' }); User.hasOne(OnboardingProfile, { foreignKey: 'userId', onDelete: 'CASCADE' }); OnboardingProfile.belongsTo(User, { foreignKey: 'userId' });
  User.hasMany(DiscoverAction, { foreignKey: 'actorUserId', onDelete: 'CASCADE', as: 'discoverActions' }); DiscoverAction.belongsTo(User, { foreignKey: 'actorUserId', as: 'actor' }); DiscoverAction.belongsTo(User, { foreignKey: 'targetUserId', as: 'target' });
  User.hasMany(Match, { foreignKey: 'userOneId', onDelete: 'CASCADE', as: 'firstMatches' }); User.hasMany(Match, { foreignKey: 'userTwoId', onDelete: 'CASCADE', as: 'secondMatches' }); Match.belongsTo(User, { foreignKey: 'userOneId', as: 'userOne' }); Match.belongsTo(User, { foreignKey: 'userTwoId', as: 'userTwo' });
  User.hasMany(Boost, { foreignKey: 'userId', onDelete: 'CASCADE', as: 'boosts' }); Boost.belongsTo(User, { foreignKey: 'userId' });
  User.hasOne(DiscoverFilterPreference, { foreignKey: 'userId', onDelete: 'CASCADE' }); DiscoverFilterPreference.belongsTo(User, { foreignKey: 'userId' });
  User.hasMany(Block, { foreignKey: 'blockerUserId', as: 'blocksCreated', onDelete: 'CASCADE' }); User.hasMany(Block, { foreignKey: 'blockedUserId', as: 'blocksReceived', onDelete: 'CASCADE' }); Block.belongsTo(User, { foreignKey: 'blockerUserId', as: 'blocker' }); Block.belongsTo(User, { foreignKey: 'blockedUserId', as: 'blockedUser' });
  User.hasMany(Report, { foreignKey: 'reporterUserId', as: 'reportsCreated' }); User.hasMany(Report, { foreignKey: 'reportedUserId', as: 'reportsReceived' }); Report.belongsTo(User, { foreignKey: 'reporterUserId', as: 'reporter' }); Report.belongsTo(User, { foreignKey: 'reportedUserId', as: 'reportedUser' });
  Report.hasMany(ReportEvidence, { foreignKey: 'reportId', as: 'evidence', onDelete: 'CASCADE' }); ReportEvidence.belongsTo(Report, { foreignKey: 'reportId', as: 'report' });
  Conversation.hasMany(ConversationParticipant, { foreignKey: 'conversationId', as: 'participants', onDelete: 'CASCADE' }); ConversationParticipant.belongsTo(Conversation, { foreignKey: 'conversationId', as: 'conversation' });
  User.hasMany(ConversationParticipant, { foreignKey: 'userId', as: 'conversationMemberships', onDelete: 'CASCADE' }); ConversationParticipant.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Conversation.hasMany(Message, { foreignKey: 'conversationId', as: 'messages', onDelete: 'CASCADE' }); Message.belongsTo(Conversation, { foreignKey: 'conversationId', as: 'conversation' });
  User.hasMany(Message, { foreignKey: 'senderId', as: 'sentMessages' }); Message.belongsTo(User, { foreignKey: 'senderId', as: 'sender' });
  Message.hasMany(MessageMedia, { foreignKey: 'messageId', as: 'media', onDelete: 'CASCADE' }); MessageMedia.belongsTo(Message, { foreignKey: 'messageId', as: 'message' });
  Conversation.belongsTo(Message, { foreignKey: 'lastMessageId', as: 'lastMessage', constraints: false }); ConversationParticipant.belongsTo(Message, { foreignKey: 'lastReadMessageId', as: 'lastReadMessage', constraints: false });
  User.hasMany(Event, { foreignKey: 'hostId', as: 'hostedEvents' }); Event.belongsTo(User, { foreignKey: 'hostId', as: 'host' });
  Event.hasMany(EventRegistration, { foreignKey: 'eventId', as: 'registrations', onDelete: 'CASCADE' }); EventRegistration.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventRegistration, { foreignKey: 'userId', as: 'eventRegistrations', onDelete: 'CASCADE' }); EventRegistration.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventWaitlist, { foreignKey: 'eventId', as: 'waitlist', onDelete: 'CASCADE' }); EventWaitlist.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventWaitlist, { foreignKey: 'userId', as: 'eventWaitlistEntries', onDelete: 'CASCADE' }); EventWaitlist.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventFeedback, { foreignKey: 'eventId', as: 'feedback', onDelete: 'RESTRICT' }); EventFeedback.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventFeedback, { foreignKey: 'userId', as: 'eventFeedback', onDelete: 'RESTRICT' }); EventFeedback.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventCheckIn, { foreignKey: 'eventId', as: 'checkIns', onDelete: 'RESTRICT' }); EventCheckIn.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventCheckIn, { foreignKey: 'userId', as: 'eventCheckIns', onDelete: 'RESTRICT' }); EventCheckIn.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventGroupMessage, { foreignKey: 'eventId', as: 'groupMessages', onDelete: 'CASCADE' }); EventGroupMessage.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventGroupMessage, { foreignKey: 'senderId', as: 'eventGroupMessages', onDelete: 'RESTRICT' }); EventGroupMessage.belongsTo(User, { foreignKey: 'senderId', as: 'sender' });
  models = { User, OtpToken, RefreshToken, OnboardingProfile, DiscoverAction, Match, Boost, DiscoverFilterPreference, Block, Report, ReportEvidence, Conversation, ConversationParticipant, Message, MessageMedia, Event, EventRegistration, EventWaitlist, EventFeedback, EventCheckIn, EventGroupMessage }; return models;
}
function getModels() { if (!models.User) throw new Error('Models are not initialized.'); return models; }
module.exports = { initModels, getModels };
