const defineUser = require('./User'); const defineOtpToken = require('./OtpToken'); const defineRefreshToken = require('./RefreshToken'); const defineOnboardingProfile = require('./OnboardingProfile'); const defineDiscoverAction = require('./DiscoverAction'); const defineMatch = require('./Match'); const defineBoost = require('./Boost'); const defineDiscoverFilterPreference = require('./DiscoverFilterPreference'); const defineBlock = require('./Block'); const defineReport = require('./Report'); const defineReportEvidence = require('./ReportEvidence');
let models = {};
function initModels(sequelize) {
  if (models.User) return models;
  const User = defineUser(sequelize); const OtpToken = defineOtpToken(sequelize); const RefreshToken = defineRefreshToken(sequelize); const OnboardingProfile = defineOnboardingProfile(sequelize); const DiscoverAction = defineDiscoverAction(sequelize); const Match = defineMatch(sequelize); const Boost = defineBoost(sequelize); const DiscoverFilterPreference = defineDiscoverFilterPreference(sequelize); const Block = defineBlock(sequelize); const Report = defineReport(sequelize); const ReportEvidence = defineReportEvidence(sequelize);
  User.hasMany(RefreshToken, { foreignKey: 'userId', onDelete: 'CASCADE' }); RefreshToken.belongsTo(User, { foreignKey: 'userId' }); User.hasOne(OnboardingProfile, { foreignKey: 'userId', onDelete: 'CASCADE' }); OnboardingProfile.belongsTo(User, { foreignKey: 'userId' });
  User.hasMany(DiscoverAction, { foreignKey: 'actorUserId', onDelete: 'CASCADE', as: 'discoverActions' }); DiscoverAction.belongsTo(User, { foreignKey: 'actorUserId', as: 'actor' }); DiscoverAction.belongsTo(User, { foreignKey: 'targetUserId', as: 'target' });
  User.hasMany(Match, { foreignKey: 'userOneId', onDelete: 'CASCADE', as: 'firstMatches' }); User.hasMany(Match, { foreignKey: 'userTwoId', onDelete: 'CASCADE', as: 'secondMatches' }); Match.belongsTo(User, { foreignKey: 'userOneId', as: 'userOne' }); Match.belongsTo(User, { foreignKey: 'userTwoId', as: 'userTwo' });
  User.hasMany(Boost, { foreignKey: 'userId', onDelete: 'CASCADE', as: 'boosts' }); Boost.belongsTo(User, { foreignKey: 'userId' });
  User.hasOne(DiscoverFilterPreference, { foreignKey: 'userId', onDelete: 'CASCADE' }); DiscoverFilterPreference.belongsTo(User, { foreignKey: 'userId' });
  User.hasMany(Block, { foreignKey: 'blockerUserId', as: 'blocksCreated', onDelete: 'CASCADE' }); User.hasMany(Block, { foreignKey: 'blockedUserId', as: 'blocksReceived', onDelete: 'CASCADE' }); Block.belongsTo(User, { foreignKey: 'blockerUserId', as: 'blocker' }); Block.belongsTo(User, { foreignKey: 'blockedUserId', as: 'blockedUser' });
  User.hasMany(Report, { foreignKey: 'reporterUserId', as: 'reportsCreated' }); User.hasMany(Report, { foreignKey: 'reportedUserId', as: 'reportsReceived' }); Report.belongsTo(User, { foreignKey: 'reporterUserId', as: 'reporter' }); Report.belongsTo(User, { foreignKey: 'reportedUserId', as: 'reportedUser' });
  Report.hasMany(ReportEvidence, { foreignKey: 'reportId', as: 'evidence', onDelete: 'CASCADE' }); ReportEvidence.belongsTo(Report, { foreignKey: 'reportId', as: 'report' });
  models = { User, OtpToken, RefreshToken, OnboardingProfile, DiscoverAction, Match, Boost, DiscoverFilterPreference, Block, Report, ReportEvidence }; return models;
}
function getModels() { if (!models.User) throw new Error('Models are not initialized.'); return models; }
module.exports = { initModels, getModels };
