const definitions = {
  User: require('./User'), OtpToken: require('./OtpToken'), RefreshToken: require('./RefreshToken'), OnboardingProfile: require('./OnboardingProfile'),
  DiscoverAction: require('./DiscoverAction'), Match: require('./Match'), Boost: require('./Boost'), DiscoverFilterPreference: require('./DiscoverFilterPreference'),
  Block: require('./Block'), Report: require('./Report'), ReportEvidence: require('./ReportEvidence'), Conversation: require('./Conversation'),
  ConversationParticipant: require('./ConversationParticipant'), Message: require('./Message'), MessageMedia: require('./MessageMedia'), Event: require('./Event'),
  EventRegistration: require('./EventRegistration'), EventWaitlist: require('./EventWaitlist'), EventFeedback: require('./EventFeedback'), EventCheckIn: require('./EventCheckIn'), EventGroupMessage: require('./EventGroupMessage'),
  SubscriptionPlan: require('./SubscriptionPlan'), Subscription: require('./Subscription'), Payment: require('./Payment'), PaymentEvent: require('./PaymentEvent'),
  Wallet: require('./Wallet'), WalletTransaction: require('./WalletTransaction'), WalletProduct: require('./WalletProduct'), BoostProduct: require('./BoostProduct'),
  BoostEntitlement: require('./BoostEntitlement'), Gift: require('./Gift'), GiftTransaction: require('./GiftTransaction'),
  SavedProfile: require('./SavedProfile'), NotificationPreference: require('./NotificationPreference'), Notification: require('./Notification'),
};
let models = {};
function initModels(sequelize) {
  if (models.User) return models;
  const created = Object.fromEntries(Object.entries(definitions).map(([name, define]) => [name, define(sequelize)]));
  const { User, RefreshToken, OnboardingProfile, DiscoverAction, Match, Boost, DiscoverFilterPreference, Block, Report, ReportEvidence, Conversation, ConversationParticipant, Message, MessageMedia, Event, EventRegistration, EventWaitlist, EventFeedback, EventCheckIn, EventGroupMessage, SubscriptionPlan, Subscription, Payment, PaymentEvent, Wallet, WalletTransaction, WalletProduct, BoostProduct, BoostEntitlement, Gift, GiftTransaction, SavedProfile, NotificationPreference, Notification } = created;
  User.hasMany(RefreshToken, { foreignKey: 'userId', onDelete: 'CASCADE' }); RefreshToken.belongsTo(User, { foreignKey: 'userId' }); User.hasOne(OnboardingProfile, { foreignKey: 'userId', onDelete: 'CASCADE' }); OnboardingProfile.belongsTo(User, { foreignKey: 'userId' });
  User.hasMany(DiscoverAction, { foreignKey: 'actorUserId', onDelete: 'CASCADE', as: 'discoverActions' }); DiscoverAction.belongsTo(User, { foreignKey: 'actorUserId', as: 'actor' }); DiscoverAction.belongsTo(User, { foreignKey: 'targetUserId', as: 'target' });
  User.hasMany(Match, { foreignKey: 'userOneId', onDelete: 'CASCADE', as: 'firstMatches' }); User.hasMany(Match, { foreignKey: 'userTwoId', onDelete: 'CASCADE', as: 'secondMatches' }); Match.belongsTo(User, { foreignKey: 'userOneId', as: 'userOne' }); Match.belongsTo(User, { foreignKey: 'userTwoId', as: 'userTwo' });
  User.hasMany(Boost, { foreignKey: 'userId', onDelete: 'CASCADE', as: 'boosts' }); Boost.belongsTo(User, { foreignKey: 'userId' });
  User.hasOne(DiscoverFilterPreference, { foreignKey: 'userId', onDelete: 'CASCADE' }); DiscoverFilterPreference.belongsTo(User, { foreignKey: 'userId' });
  User.hasMany(SavedProfile, { foreignKey: 'userId', as: 'savedProfiles', onDelete: 'CASCADE' }); SavedProfile.belongsTo(User, { foreignKey: 'userId', as: 'owner' }); SavedProfile.belongsTo(User, { foreignKey: 'savedUserId', as: 'savedUser' });
  User.hasOne(NotificationPreference, { foreignKey: 'userId', as: 'notificationPreference', onDelete: 'CASCADE' }); NotificationPreference.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  User.hasMany(Notification, { foreignKey: 'userId', as: 'notifications', onDelete: 'CASCADE' }); Notification.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  User.hasMany(Block, { foreignKey: 'blockerUserId', as: 'blocksCreated', onDelete: 'CASCADE' }); User.hasMany(Block, { foreignKey: 'blockedUserId', as: 'blocksReceived', onDelete: 'CASCADE' }); Block.belongsTo(User, { foreignKey: 'blockerUserId', as: 'blocker' }); Block.belongsTo(User, { foreignKey: 'blockedUserId', as: 'blockedUser' });
  User.hasMany(Report, { foreignKey: 'reporterUserId', as: 'reportsCreated' }); User.hasMany(Report, { foreignKey: 'reportedUserId', as: 'reportsReceived' }); Report.belongsTo(User, { foreignKey: 'reporterUserId', as: 'reporter' }); Report.belongsTo(User, { foreignKey: 'reportedUserId', as: 'reportedUser' });
  Report.hasMany(ReportEvidence, { foreignKey: 'reportId', as: 'evidence', onDelete: 'CASCADE' }); ReportEvidence.belongsTo(Report, { foreignKey: 'reportId', as: 'report' });
  Conversation.hasMany(ConversationParticipant, { foreignKey: 'conversationId', as: 'participants', onDelete: 'CASCADE' }); ConversationParticipant.belongsTo(Conversation, { foreignKey: 'conversationId', as: 'conversation' });
  User.hasMany(ConversationParticipant, { foreignKey: 'userId', as: 'conversationMemberships', onDelete: 'CASCADE' }); ConversationParticipant.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Conversation.hasMany(Message, { foreignKey: 'conversationId', as: 'messages', onDelete: 'CASCADE' }); Message.belongsTo(Conversation, { foreignKey: 'conversationId', as: 'conversation' });
  User.hasMany(Message, { foreignKey: 'senderId', as: 'sentMessages' }); Message.belongsTo(User, { foreignKey: 'senderId', as: 'sender' });
  Message.hasMany(MessageMedia, { foreignKey: 'messageId', as: 'media', onDelete: 'CASCADE' }); MessageMedia.belongsTo(Message, { foreignKey: 'messageId', as: 'message' });
  Conversation.belongsTo(Message, { foreignKey: 'lastMessageId', as: 'lastMessage', constraints: false }); ConversationParticipant.belongsTo(Message, { foreignKey: 'lastReadMessageId', as: 'lastReadMessage', constraints: false });
  User.hasMany(Event, { foreignKey: 'hostId', as: 'hostedEvents' }); Event.belongsTo(User, { foreignKey: 'hostId', as: 'host' });
  Event.hasMany(EventRegistration, { foreignKey: 'eventId', as: 'registrations', onDelete: 'CASCADE' }); EventRegistration.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventRegistration, { foreignKey: 'userId', as: 'eventRegistrations', onDelete: 'CASCADE' }); EventRegistration.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventWaitlist, { foreignKey: 'eventId', as: 'waitlist', onDelete: 'CASCADE' }); EventWaitlist.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventWaitlist, { foreignKey: 'userId', as: 'eventWaitlistEntries', onDelete: 'CASCADE' }); EventWaitlist.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventFeedback, { foreignKey: 'eventId', as: 'feedback', onDelete: 'RESTRICT' }); EventFeedback.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventFeedback, { foreignKey: 'userId', as: 'eventFeedback', onDelete: 'RESTRICT' }); EventFeedback.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventCheckIn, { foreignKey: 'eventId', as: 'checkIns', onDelete: 'RESTRICT' }); EventCheckIn.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventCheckIn, { foreignKey: 'userId', as: 'eventCheckIns', onDelete: 'RESTRICT' }); EventCheckIn.belongsTo(User, { foreignKey: 'userId', as: 'user' });
  Event.hasMany(EventGroupMessage, { foreignKey: 'eventId', as: 'groupMessages', onDelete: 'CASCADE' }); EventGroupMessage.belongsTo(Event, { foreignKey: 'eventId', as: 'event' }); User.hasMany(EventGroupMessage, { foreignKey: 'senderId', as: 'eventGroupMessages', onDelete: 'RESTRICT' }); EventGroupMessage.belongsTo(User, { foreignKey: 'senderId', as: 'sender' });
  User.hasOne(Subscription, { foreignKey: 'userId', as: 'subscription' }); Subscription.belongsTo(User, { foreignKey: 'userId', as: 'user' }); SubscriptionPlan.hasMany(Subscription, { foreignKey: 'planId', as: 'subscriptions' }); Subscription.belongsTo(SubscriptionPlan, { foreignKey: 'planId', as: 'plan' });
  User.hasMany(Payment, { foreignKey: 'userId', as: 'payments' }); Payment.belongsTo(User, { foreignKey: 'userId', as: 'user' }); SubscriptionPlan.hasMany(Payment, { foreignKey: 'planId', as: 'payments' }); Payment.belongsTo(SubscriptionPlan, { foreignKey: 'planId', as: 'plan' }); Payment.hasMany(PaymentEvent, { foreignKey: 'paymentId', as: 'events' }); PaymentEvent.belongsTo(Payment, { foreignKey: 'paymentId', as: 'payment' });
  User.hasOne(Wallet, { foreignKey: 'userId', as: 'wallet' }); Wallet.belongsTo(User, { foreignKey: 'userId', as: 'user' }); Wallet.hasMany(WalletTransaction, { foreignKey: 'walletId', as: 'transactions' }); WalletTransaction.belongsTo(Wallet, { foreignKey: 'walletId', as: 'wallet' }); User.hasMany(WalletTransaction, { foreignKey: 'userId', as: 'walletTransactions' });
  User.hasMany(BoostEntitlement, { foreignKey: 'userId', as: 'boostEntitlements' }); BoostEntitlement.belongsTo(User, { foreignKey: 'userId', as: 'user' }); BoostProduct.hasMany(BoostEntitlement, { foreignKey: 'productId', as: 'entitlements' }); BoostEntitlement.belongsTo(BoostProduct, { foreignKey: 'productId', as: 'product' }); BoostEntitlement.hasMany(Boost, { foreignKey: 'boostEntitlementId', as: 'activations' }); Boost.belongsTo(BoostEntitlement, { foreignKey: 'boostEntitlementId', as: 'entitlement' });
  Gift.hasMany(GiftTransaction, { foreignKey: 'giftId', as: 'transactions' }); GiftTransaction.belongsTo(Gift, { foreignKey: 'giftId', as: 'gift' }); User.hasMany(GiftTransaction, { foreignKey: 'senderId', as: 'giftsSent' }); User.hasMany(GiftTransaction, { foreignKey: 'recipientId', as: 'giftsReceived' }); GiftTransaction.belongsTo(User, { foreignKey: 'senderId', as: 'sender' }); GiftTransaction.belongsTo(User, { foreignKey: 'recipientId', as: 'recipient' });
  models = created; return models;
}
function getModels() { if (!models.User) throw new Error('Models are not initialized.'); return models; }
module.exports = { initModels, getModels };
