const { DataTypes } = require('sequelize');
const { COMMUNICATION_STYLE_VALUES } = require('../constants/communicationStyles');
const jsonValue = (field, fallback) => ({ type: DataTypes.JSON, allowNull: false, defaultValue: fallback, get() { const value = this.getDataValue(field); if (typeof value !== 'string') return value ?? fallback; try { return JSON.parse(value); } catch (_) { return fallback; } } });
module.exports = (sequelize) => {
return sequelize.define('OnboardingProfile', {
  id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  userId: { type: DataTypes.INTEGER, allowNull: false, unique: true },
  birthDate: { type: DataTypes.DATEONLY, allowNull: true }, gender: { type: DataTypes.STRING, allowNull: true }, customGender: { type: DataTypes.STRING, allowNull: false, defaultValue: '' }, interestedIn: jsonValue('interestedIn', []), relationshipGoals: jsonValue('relationshipGoals', []), city: { type: DataTypes.STRING, allowNull: true }, preferredDistance: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 50 }, profession: { type: DataTypes.STRING, allowNull: true }, company: { type: DataTypes.STRING, allowNull: true }, education: { type: DataTypes.STRING, allowNull: true }, bio: { type: DataTypes.TEXT, allowNull: true }, hometown: { type: DataTypes.STRING, allowNull: false, defaultValue: '' }, interests: jsonValue('interests', []), lifestyle: jsonValue('lifestyle', {}), prompts: jsonValue('prompts', {}), pronouns: jsonValue('pronouns', []), sexuality: { type: DataTypes.STRING, allowNull: false, defaultValue: '' }, valuedQualities: jsonValue('valuedQualities', []), loveLanguages: jsonValue('loveLanguages', []), preferredTalkingHours: jsonValue('preferredTalkingHours', []), communicationStyle: { type: DataTypes.ENUM(...COMMUNICATION_STYLE_VALUES), allowNull: true }, photos: jsonValue('photos', []), primaryPhotoIndex: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 }, voicePromptUrl: { type: DataTypes.STRING, allowNull: true }, videoPromptUrl: { type: DataTypes.STRING, allowNull: true }, personality: { type: DataTypes.STRING, allowNull: true }, travelPreference: { type: DataTypes.STRING, allowNull: true }, musicTaste: { type: DataTypes.STRING, allowNull: true }, foodPreference: { type: DataTypes.STRING, allowNull: true }, weekendPlan: { type: DataTypes.STRING, allowNull: true }, petPreference: { type: DataTypes.STRING, allowNull: true }, coffeePreference: { type: DataTypes.STRING, allowNull: true }, height: { type: DataTypes.STRING, allowNull: true }, fitnessLevel: { type: DataTypes.STRING, allowNull: true }, children: { type: DataTypes.STRING, allowNull: true }, smoking: { type: DataTypes.STRING, allowNull: true }, drinking: { type: DataTypes.STRING, allowNull: true }, weed: { type: DataTypes.STRING, allowNull: true }, community: { type: DataTypes.STRING, allowNull: true }, religion: { type: DataTypes.STRING, allowNull: true }, familyValues: { type: DataTypes.STRING, allowNull: true }, loveLanguage: { type: DataTypes.STRING, allowNull: true }, languages: jsonValue('languages', []), greenFlags: jsonValue('greenFlags', []), redFlags: jsonValue('redFlags', []), dateIdeas: jsonValue('dateIdeas', []), stage: { type: DataTypes.ENUM('age', 'gender', 'interestedIn', 'relationshipGoal', 'location', 'starterProfile', 'profileCompletion', 'photos', 'complete'), allowNull: false, defaultValue: 'age' }, onboardingCompleted: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false }
}, { tableName: 'OnboardingProfiles' });
};
