const { Op } = require('sequelize'); const { getModels } = require('../models'); const fileCleanup = require('./accountDeletionFileCleanupService');
const DELETION_TREATMENTS = Object.freeze({ DELETE: 'DELETE', ANONYMIZE: 'ANONYMIZE', RETAIN: 'RETAIN', RETENTION_DECISION_REQUIRED: 'RETENTION_DECISION_REQUIRED', NOT_APPLICABLE: 'NOT_APPLICABLE' });
const FAILURE_CODES = Object.freeze({ PROFILE_MEDIA: 'PROFILE_MEDIA_CLEANUP_FAILED', AUTH: 'AUTH_ARTIFACT_CLEANUP_FAILED', RELATIONSHIPS: 'RELATIONSHIP_CLEANUP_FAILED', NOTIFICATIONS: 'NOTIFICATION_CLEANUP_FAILED', PROFILE: 'PROFILE_CLEANUP_FAILED', USER: 'USER_RECORD_CLEANUP_FAILED', UNKNOWN: 'UNKNOWN_DELETION_ERROR' });
const done = (category, treatment, affectedRows = 0) => ({ category, treatment, status: 'COMPLETED', affectedRows });
const review = (category, reason, affectedRows) => affectedRows ? { category, treatment: DELETION_TREATMENTS.RETENTION_DECISION_REQUIRED, status: 'BLOCKED', reason, affectedRows } : done(category, DELETION_TREATMENTS.NOT_APPLICABLE);

class AccountDeletionService {
  constructor({ models = getModels, backupRetentionApproved = false } = {}) { this.models = models; this.backupRetentionApproved = backupRetentionApproved; }
  async execute({ userId, deletionRequestId, correlationId, deletionReason, deletionDetails }) {
    const claim = await this.claimRequest({ userId, deletionRequestId, correlationId }); if (!claim.claimed) return claim;
    const { AccountDeletionRequest } = this.models();
    try {
      const results = [await this.handleSessions(userId), await this.handleOtps(userId), await this.handleUserDevices(userId), await this.handleProfilePhotos(userId, deletionRequestId, correlationId), await this.handleProfile(userId), await this.handleLikes(userId), await this.handleSuperLikes(userId), await this.handleRoses(userId), await this.handleSavedProfiles(userId), await this.handleMatches(userId), await this.handleBlocks(userId), await this.handleNotifications(userId), ...await this.handleRetentionCategories(userId)];
      const blocked = results.filter((result) => result.status === 'BLOCKED');
      if (blocked.length) { await AccountDeletionRequest.update({ status: 'BLOCKED_BY_RETENTION_DECISION', legalHold: true, legalHoldReason: blocked[0].reason }, { where: { id: deletionRequestId, status: 'PROCESSING' } }); return { status: 'BLOCKED_BY_RETENTION_DECISION', blocked: true, categoryResults: results }; }
      results.push(await this.handleUserAnonymization({ userId, deletionReason, deletionDetails }));
      await AccountDeletionRequest.update({ status: 'COMPLETED', completedAt: new Date(), failedAt: null, failureCode: null, legalHold: false, legalHoldReason: null }, { where: { id: deletionRequestId, status: 'PROCESSING' } });
      return { status: 'COMPLETED', completed: true, categoryResults: results };
    } catch (error) { const failureCode = error.deletionFailureCode || FAILURE_CODES.UNKNOWN; await this.markFailed({ deletionRequestId, failureCode }); return { status: 'FAILED', failed: true, failureCode }; }
  }
  async claimRequest({ userId, deletionRequestId, correlationId }) { const { AccountDeletionRequest } = this.models(); return AccountDeletionRequest.sequelize.transaction(async (transaction) => { const request = await AccountDeletionRequest.findByPk(deletionRequestId, { transaction, lock: transaction.LOCK.UPDATE }); if (!request || request.userId !== Number(userId) || request.correlationId !== correlationId) return { status: 'INVALID', invalid: true }; if (request.status === 'COMPLETED') return { status: 'COMPLETED', alreadyCompleted: true }; if (request.status === 'PROCESSING') return { status: 'PROCESSING', alreadyProcessing: true }; if (request.status === 'FAILED') return { status: 'FAILED', alreadyFailed: true, failureCode: request.failureCode }; if (request.status === 'BLOCKED_BY_RETENTION_DECISION') return { status: request.status, blocked: true }; if (request.status === 'PENDING') return { status: 'PENDING', notVerified: true }; if (request.status !== 'VERIFIED') return { status: request.status, invalid: true }; request.status = 'PROCESSING'; request.processingStartedAt = new Date(); await request.save({ transaction }); return { status: 'PROCESSING', claimed: true }; }); }
  async destroy(category, treatment, models, userId, code) { try { let affectedRows = 0; for (const model of models) affectedRows += await this.models()[model].destroy({ where: { userId } }); return done(category, treatment, affectedRows); } catch (error) { error.deletionFailureCode = code; throw error; } }
  async destroyWhere(category, model, where) { try { return done(category, DELETION_TREATMENTS.DELETE, await this.models()[model].destroy({ where })); } catch (error) { error.deletionFailureCode = FAILURE_CODES.RELATIONSHIPS; throw error; } }
  handleSessions(userId) { return this.destroy('SESSIONS', DELETION_TREATMENTS.DELETE, ['RefreshToken', 'AccountDeletionConfirmation'], userId, FAILURE_CODES.AUTH); }
  handleUserDevices(userId) { return this.destroy('USER_DEVICES', DELETION_TREATMENTS.DELETE, ['UserDevice'], userId, FAILURE_CODES.AUTH); }
  async handleOtps(userId) { const { User, OtpToken } = this.models(); try { const user = await User.findByPk(userId, { attributes: ['email', 'phoneNumber'] }); return done('OTPS', DELETION_TREATMENTS.DELETE, user ? await OtpToken.destroy({ where: { [Op.or]: [{ email: user.email }, { phoneNumber: user.phoneNumber }] } }) : 0); } catch (error) { error.deletionFailureCode = FAILURE_CODES.AUTH; throw error; } }
  async handleProfilePhotos(userId, accountDeletionRequestId, correlationId) { const { OnboardingProfile } = this.models(); try { const profile = await OnboardingProfile.findOne({ where: { userId }, attributes: ['photos'] }); let affectedRows = 0; for (const photo of profile?.photos || []) { const task = await fileCleanup.createAndExecute({ accountDeletionRequestId, correlationId, storageKey: photo }); if (task.status !== 'COMPLETED') throw new Error('Profile photo cleanup task did not complete.'); affectedRows += 1; } return done('PROFILE_PHOTOS', DELETION_TREATMENTS.DELETE, affectedRows); } catch (error) { error.deletionFailureCode = FAILURE_CODES.PROFILE_MEDIA; throw error; } }
  handleProfile(userId) { return this.destroy('PROFILE', DELETION_TREATMENTS.DELETE, ['OnboardingProfile', 'DiscoverFilterPreference', 'NotificationPreference'], userId, FAILURE_CODES.PROFILE); }
  handleLikes(userId) { return this.destroyWhere('LIKES', 'DiscoverAction', { action: 'like', [Op.or]: [{ actorUserId: userId }, { targetUserId: userId }] }); }
  handleSuperLikes(userId) { return this.destroyWhere('SUPER_LIKES', 'DiscoverAction', { action: 'superLike', [Op.or]: [{ actorUserId: userId }, { targetUserId: userId }] }); }
  handleRoses(userId) { return this.destroyWhere('ROSES', 'RoseTransaction', { [Op.or]: [{ senderId: userId }, { recipientId: userId }] }); }
  handleSavedProfiles(userId) { return this.destroyWhere('SAVED_PROFILES', 'SavedProfile', { [Op.or]: [{ userId }, { savedUserId: userId }] }); }
  handleMatches(userId) { return this.destroyWhere('MATCHES', 'Match', { [Op.or]: [{ userOneId: userId }, { userTwoId: userId }] }); }
  handleBlocks(userId) { return this.destroyWhere('BLOCKS', 'Block', { [Op.or]: [{ blockerUserId: userId }, { blockedUserId: userId }] }); }
  async handleNotifications(userId) { const { Notification } = this.models(); try { const deleted = await Notification.destroy({ where: { userId } }); const anonymized = (await Notification.update({ actorUserId: null }, { where: { actorUserId: userId } }))[0]; return done('NOTIFICATIONS', DELETION_TREATMENTS.ANONYMIZE, deleted + anonymized); } catch (error) { error.deletionFailureCode = FAILURE_CODES.NOTIFICATIONS; throw error; } }
  async handleRetentionCategories(userId) { const m = this.models(); const messages = await m.Message.count({ where: { senderId: userId } }); const values = await Promise.all([m.ConversationParticipant.count({ where: { userId } }), m.IdentityVerification.count({ where: { userId } }), m.Report.count({ where: { [Op.or]: [{ reporterUserId: userId }, { reportedUserId: userId }] } }), m.Payment.count({ where: { userId } }), m.Subscription.count({ where: { userId } }), m.UserLoginEvent.count({ where: { userId } }), m.UserTimelineEvent.count({ where: { userId } }), m.EventRegistration.count({ where: { userId } }), m.EventWaitlist.count({ where: { userId } }), m.ConsentEvent.count({ where: { userId } })]); return [review('CONVERSATIONS', 'SHARED_CONVERSATION_POLICY_REQUIRED', values[0]), review('MESSAGES', 'SHARED_MESSAGE_POLICY_REQUIRED', messages), review('CHAT_MEDIA', 'SHARED_CHAT_MEDIA_POLICY_REQUIRED', await m.Message.count({ where: { senderId: userId, type: 'image' } })), review('IDENTITY_VERIFICATION', 'IDENTITY_RETENTION_REVIEW_REQUIRED', values[1]), review('REPORTS_AND_MODERATION', 'SAFETY_RECORD_RETENTION_REVIEW_REQUIRED', values[2]), review('PAYMENTS', 'FINANCIAL_RETENTION_REVIEW_REQUIRED', values[3]), review('SUBSCRIPTIONS', 'FINANCIAL_RETENTION_REVIEW_REQUIRED', values[4]), review('SECURITY_AND_AUDIT', 'SECURITY_AUDIT_RETENTION_REVIEW_REQUIRED', values[5] + values[6]), review('EVENT_PARTICIPATION', 'EVENT_PARTICIPATION_POLICY_REQUIRED', values[7] + values[8]), review('CONSENT_EVIDENCE', 'CONSENT_RETENTION_DECISION_REQUIRED', values[9]), this.backupRetentionApproved ? done('BACKUPS', DELETION_TREATMENTS.RETAIN) : review('BACKUPS', 'BACKUP_RETENTION_REVIEW_REQUIRED', 1), done('AI_DATA', DELETION_TREATMENTS.NOT_APPLICABLE)]; }
  async handleUserAnonymization({ userId, deletionReason, deletionDetails }) { const { User } = this.models(); try { await User.sequelize.transaction(async (transaction) => { const user = await User.findByPk(userId, { transaction, lock: transaction.LOCK.UPDATE }); if (!user || user.accountStatus === 'deleted') return; const identity = `deleted-${user.id}-${Date.now()}`; Object.assign(user, { accountStatus: 'deleted', deletedAt: new Date(), deactivatedAt: null, tokenVersion: user.tokenVersion + 1, deletionReason, deletionDetails: deletionDetails || null, name: 'Deleted Member', email: `${identity}@deleted.amora.invalid`, phoneNumber: identity, passwordHash: null, googleId: null, isVerified: false }); await user.save({ transaction }); }); return done('USER_ACCOUNT', DELETION_TREATMENTS.ANONYMIZE, 1); } catch (error) { error.deletionFailureCode = FAILURE_CODES.USER; throw error; } }
  async markFailed({ deletionRequestId, failureCode }) { await this.models().AccountDeletionRequest.update({ status: 'FAILED', failedAt: new Date(), failureCode }, { where: { id: deletionRequestId, status: 'PROCESSING' } }); }
}
module.exports = new AccountDeletionService(); module.exports.AccountDeletionService = AccountDeletionService; module.exports.DELETION_TREATMENTS = DELETION_TREATMENTS; module.exports.FAILURE_CODES = FAILURE_CODES;
