const fs = require('fs'); const path = require('path'); const { getModels } = require('../models'); const { uploadDirectory } = require('../utils/photoStorage');
class AccountDeletionFileCleanupService {
  async createAndExecute({ accountDeletionRequestId, correlationId, storageKey }) { const { AccountDeletionFileTask } = getModels(); const [task] = await AccountDeletionFileTask.findOrCreate({ where: { accountDeletionRequestId, category: 'PROFILE_PHOTO', storageKey }, defaults: { storageType: 'local_public', correlationId } }); return this.execute(task.id); }
  async execute(taskId) { const { AccountDeletionFileTask } = getModels(); const task = await AccountDeletionFileTask.sequelize.transaction(async (transaction) => { const current = await AccountDeletionFileTask.findByPk(taskId, { transaction, lock: transaction.LOCK.UPDATE }); if (!current || current.status === 'COMPLETED' || current.status === 'PROCESSING') return current; current.status = 'PROCESSING'; current.attemptCount += 1; current.lastAttemptAt = new Date(); await current.save({ transaction }); current._claimedForCleanup = true; return current; }); if (!task || task.status === 'COMPLETED' || (task.status === 'PROCESSING' && !task._claimedForCleanup)) return task;
    try { await deletePublicPhoto(task.storageKey); await task.update({ status: 'COMPLETED', completedAt: new Date(), failedAt: null, failureCode: null }); return task; } catch (error) { const code = error.code === 'INVALID_STORAGE_REFERENCE' ? error.code : 'FILE_DELETE_FAILED'; await task.update({ status: 'FAILED', failedAt: new Date(), failureCode: code }); throw error; }
  }
}
async function deletePublicPhoto(storageKey) { if (!/^\/uploads\/onboarding-photos\/[A-Za-z0-9._-]+$/.test(String(storageKey))) throw Object.assign(new Error('Invalid storage reference.'), { code: 'INVALID_STORAGE_REFERENCE' }); const root = path.resolve(uploadDirectory); const target = path.resolve(root, path.basename(storageKey)); if (!target.startsWith(`${root}${path.sep}`)) throw Object.assign(new Error('Invalid storage reference.'), { code: 'INVALID_STORAGE_REFERENCE' }); try { await fs.promises.unlink(target); } catch (error) { if (error.code !== 'ENOENT') throw error; } }
module.exports = new AccountDeletionFileCleanupService(); module.exports.AccountDeletionFileCleanupService = AccountDeletionFileCleanupService;
