const bcrypt = require('bcrypt'); const jwt = require('jsonwebtoken'); const { Op } = require('sequelize'); const { OAuth2Client } = require('google-auth-library');
const { getModels } = require('../models'); const generateOtp = require('../utils/generateOtp'); const sendSms = require('../utils/sendSms'); const { issueTokens, accessToken } = require('../utils/generateTokens');
const googleIds = (process.env.GOOGLE_CLIENT_IDS || '').split(',').map((id) => id.trim()).filter((id) => id && id !== 'skip-for-now');
const googleClient = googleIds.length ? new OAuth2Client() : null;
const profile = (user) => ({ id: user.id, name: user.name, email: user.email, phoneNumber: user.phoneNumber, isVerified: user.isVerified });
const emailOf = (value) => String(value || '').trim().toLowerCase();
const phoneOf = (value) => { const digits = String(value || '').replace(/\D/g, ''); const national = digits.length === 12 && digits.startsWith('91') ? digits.slice(2) : digits; return /^\d{10}$/.test(national) ? `+91${national}` : ''; };
async function createOtp(phoneNumber, purpose) {
  const { OtpToken } = getModels(); const code = generateOtp(); const expiresAt = new Date(Date.now() + 10 * 60 * 1000);
  await OtpToken.update({ consumed: true }, { where: { phoneNumber, purpose, consumed: false } });
  await OtpToken.create({ phoneNumber, purpose, codeHash: await bcrypt.hash(code, 12), expiresAt });
  await sendSms(phoneNumber, `Your Amora AI verification code is ${code}. It expires in 10 minutes.`, { code, purpose, expiresAt });
  return code;
}
function success(res, message, data, devOtp) { const body = { success: true, message, data }; if (process.env.NODE_ENV === 'development' && devOtp) body.devOtp = devOtp; return res.json(body); }
async function verifyOtp(identifier, code, purpose) {
  const { OtpToken } = getModels(); const otp = await OtpToken.findOne({ where: { phoneNumber: identifier, purpose, consumed: false }, order: [['createdAt', 'DESC']] });
  if (!otp || otp.expiresAt <= new Date()) { if (otp) { otp.consumed = true; await otp.save(); } return { error: ['OTP_EXPIRED', 'This verification code has expired.'] }; }
  if (otp.attempts >= 5) return { error: ['OTP_MAX_ATTEMPTS', 'Maximum verification attempts reached. Request a new code.'] };
  if (!(await bcrypt.compare(code, otp.codeHash))) { otp.attempts += 1; if (otp.attempts >= 5) otp.consumed = true; await otp.save(); return { error: [otp.attempts >= 5 ? 'OTP_MAX_ATTEMPTS' : 'OTP_INVALID', otp.attempts >= 5 ? 'Maximum verification attempts reached. Request a new code.' : 'Invalid verification code.', 5 - otp.attempts] }; }
  otp.consumed = true; await otp.save(); return { otp };
}
exports.signup = async (req, res) => { const { User } = getModels(); const email = emailOf(req.body.email); if (await User.findOne({ where: { email } })) return res.status(409).json({ success: false, message: 'An account with this email already exists.', code: 'EMAIL_EXISTS', errors: [] }); const user = await User.create({ name: req.body.name.trim(), email, phoneNumber: phoneOf(req.body.phoneNumber), passwordHash: await bcrypt.hash(req.body.password, 12), termsAcceptedAt: new Date() }); const code = await createOtp(user.phoneNumber, 'account_verification'); return success(res, 'Account created. Verification code sent.', { userId: user.id, email, phoneNumber: user.phoneNumber }, code); };
exports.verifyAccount = async (req, res) => { const { User } = getModels(); const phoneNumber = phoneOf(req.body.phoneNumber); const checked = await verifyOtp(phoneNumber, req.body.code, 'account_verification'); if (checked.error) return res.status(400).json({ success: false, message: checked.error[1], code: checked.error[0], errors: checked.error[2] !== undefined ? [{ remainingAttempts: checked.error[2] }] : [] }); const user = await User.findOne({ where: { phoneNumber } }); if (!user) return res.status(400).json({ success: false, message: 'Account not found.', code: 'OTP_INVALID', errors: [] }); user.isVerified = true; await user.save(); const tokens = await issueTokens(user, req.ip); return success(res, 'Account verified.', { ...tokens, user: profile(user) }); };
exports.resendVerification = async (req, res) => { const phoneNumber = phoneOf(req.body.phoneNumber); const code = await createOtp(phoneNumber, 'account_verification'); return success(res, 'Verification code sent.', { phoneNumber }, code); };
exports.login = async (req, res) => { const { User } = getModels(); const user = await User.findOne({ where: { email: emailOf(req.body.email) } }); if (!user || user.authProvider !== 'local' || !(await bcrypt.compare(req.body.password, user.passwordHash || ''))) { const provider = user && user.authProvider === 'google'; return res.status(401).json({ success: false, message: provider ? 'This account uses Google Sign-In. Please sign in with Google.' : 'Invalid email or password.', code: 'INVALID_CREDENTIALS', errors: [] }); } if (!user.isVerified) return res.status(403).json({ success: false, message: 'Please verify your account before logging in.', code: 'ACCOUNT_NOT_VERIFIED', errors: [] }); return success(res, 'Logged in.', { ...(await issueTokens(user, req.ip)), user: profile(user) }); };
exports.google = async (req, res) => { if (!googleClient) return res.status(503).json({ success: false, message: 'Google Sign-In is not configured on this server yet.', code: 'GOOGLE_AUTH_NOT_CONFIGURED', errors: [] }); let payload; try { payload = (await googleClient.verifyIdToken({ idToken: req.body.idToken, audience: googleIds })).getPayload(); } catch (_) { return res.status(401).json({ success: false, message: 'Invalid Google ID token.', code: 'TOKEN_INVALID', errors: [] }); } if (!payload.email || !payload.sub) return res.status(401).json({ success: false, message: 'Google token is missing required profile information.', code: 'TOKEN_INVALID', errors: [] }); const { User } = getModels(); const email = emailOf(payload.email); let user = await User.findOne({ where: { email } }); let isNewUser = false; if (user && user.authProvider === 'local') return res.status(409).json({ success: false, message: 'An account with this email uses password login. Please log in with your password first.', code: 'INVALID_CREDENTIALS', errors: [] }); if (!user) { user = await User.create({ name: payload.name || email.split('@')[0], email, googleId: payload.sub, phoneNumber: '', authProvider: 'google', isVerified: true }); isNewUser = true; } return success(res, 'Google Sign-In successful.', { ...(await issueTokens(user, req.ip)), user: profile(user), isNewUser }); };
exports.forgotPassword = async (req, res) => { const { User } = getModels(); const phoneNumber = phoneOf(req.body.phoneNumber); const user = await User.findOne({ where: { phoneNumber, authProvider: 'local' } }); let code; if (user) code = await createOtp(phoneNumber, 'password_reset'); return success(res, 'If an eligible account exists, a password reset code has been sent.', {}, code); };
exports.verifyResetCode = async (req, res) => { const phoneNumber = phoneOf(req.body.phoneNumber); const checked = await verifyOtp(phoneNumber, req.body.code, 'password_reset'); if (checked.error) return res.status(400).json({ success: false, message: checked.error[1], code: checked.error[0], errors: [] }); const recoveryToken = jwt.sign({ phoneNumber, purpose: 'password_reset' }, process.env.JWT_SECRET, { expiresIn: '10m' }); return success(res, 'Reset code verified.', { recoveryToken }); };
exports.resetPassword = async (req, res) => { let payload; try { payload = jwt.verify(req.body.recoveryToken, process.env.JWT_SECRET); } catch (e) { return res.status(401).json({ success: false, message: 'Invalid or expired recovery token.', code: e.name === 'TokenExpiredError' ? 'TOKEN_EXPIRED' : 'TOKEN_INVALID', errors: [] }); } const phoneNumber = phoneOf(req.body.phoneNumber); if (payload.phoneNumber !== phoneNumber || payload.purpose !== 'password_reset') return res.status(401).json({ success: false, message: 'Recovery token does not match this request.', code: 'TOKEN_INVALID', errors: [] }); const { User, RefreshToken } = getModels(); const user = await User.findOne({ where: { phoneNumber, authProvider: 'local' } }); if (!user) return res.status(400).json({ success: false, message: 'Account not found.', code: 'INVALID_CREDENTIALS', errors: [] }); user.passwordHash = await bcrypt.hash(req.body.newPassword, 12); await user.save(); await RefreshToken.destroy({ where: { userId: user.id } }); return success(res, 'Password updated. Please log in again.', {}); };
exports.refreshToken = async (req, res) => { const { RefreshToken, User } = getModels(); const token = req.body.refreshToken; const candidates = await RefreshToken.findAll({ where: { expiresAt: { [Op.gt]: new Date() } }, include: [User] }); let match; for (const item of candidates) if (await bcrypt.compare(token, item.tokenHash)) { match = item; break; } if (!match) return res.status(401).json({ success: false, message: 'Invalid or expired refresh token.', code: 'TOKEN_INVALID', errors: [] }); const user = match.User; await match.destroy(); return success(res, 'Token refreshed.', await issueTokens(user, req.ip)); };
exports.logout = async (req, res) => { const { RefreshToken } = getModels(); const candidates = await RefreshToken.findAll({ where: { userId: req.user.sub } }); for (const item of candidates) if (await bcrypt.compare(req.body.refreshToken, item.tokenHash)) { await item.destroy(); break; } return success(res, 'Logged out', {}); };
exports.me = async (req, res) => { const { User } = getModels(); const user = await User.findByPk(req.user.sub); if (!user) return res.status(404).json({ success: false, message: 'User not found.', code: 'TOKEN_INVALID', errors: [] }); return success(res, 'Profile retrieved.', { user: profile(user) }); };
exports.logGoogleStatus = () => console.log(googleClient ? '[Google Auth] Active' : '[Google Auth] Disabled — set GOOGLE_CLIENT_IDS in .env to enable');
