const { getModels } = require('../models'); const { publicPath, remove } = require('../utils/photoStorage');
const ranks = { age: 0, gender: 1, interestedIn: 2, relationshipGoal: 3, location: 4, starterProfile: 5, profileCompletion: 6, photos: 7, complete: 8 };
const success = (res, message, profile) => res.json({ success: true, message, data: { onboarding: profile.toJSON() } });
async function getProfile(userId) { const { OnboardingProfile } = getModels(); const [profile] = await OnboardingProfile.findOrCreate({ where: { userId }, defaults: { userId } }); return profile; }
function advance(profile, stage) { if (ranks[stage] > ranks[profile.stage]) profile.stage = stage; }
async function save(res, userId, values, stage, message) { const profile = await getProfile(userId); Object.assign(profile, values); advance(profile, stage); await profile.save(); return success(res, message, profile); }
exports.status = async (req, res, next) => { try { return success(res, 'Onboarding status retrieved.', await getProfile(req.user.sub)); } catch (error) { return next(error); } };
exports.age = async (req, res, next) => { try { return save(res, req.user.sub, { birthDate: req.body.birthDate }, 'age', 'Date of birth saved.'); } catch (error) { return next(error); } };
exports.gender = async (req, res, next) => { try { return save(res, req.user.sub, { gender: req.body.gender, customGender: req.body.gender === 'Other' ? (req.body.customGender || '').trim() : '' }, 'gender', 'Gender saved.'); } catch (error) { return next(error); } };
exports.interestedIn = async (req, res, next) => { try { return save(res, req.user.sub, { interestedIn: req.body.interestedIn }, 'interestedIn', 'Interested-in preferences saved.'); } catch (error) { return next(error); } };
exports.relationshipGoal = async (req, res, next) => { try { return save(res, req.user.sub, { relationshipGoals: req.body.relationshipGoals }, 'relationshipGoal', 'Relationship goals saved.'); } catch (error) { return next(error); } };
exports.location = async (req, res, next) => { try { const values = { city: req.body.city.trim() }; if (req.body.preferredDistance !== undefined) values.preferredDistance = req.body.preferredDistance; return save(res, req.user.sub, values, 'location', 'Location saved.'); } catch (error) { return next(error); } };
exports.starterProfile = async (req, res, next) => { try { const values = { profession: req.body.profession.trim(), education: req.body.education.trim() }; if (req.body.company !== undefined) values.company = req.body.company.trim(); return save(res, req.user.sub, values, 'starterProfile', 'Starter profile saved.'); } catch (error) { return next(error); } };
exports.profileCompletion = async (req, res, next) => { try { const fields = ['bio', 'interests', 'lifestyle', 'prompts', 'hometown', 'pronouns', 'sexuality', 'valuedQualities', 'loveLanguages', 'preferredTalkingHours', 'voicePromptUrl', 'videoPromptUrl']; const values = {}; for (const field of fields) if (Object.prototype.hasOwnProperty.call(req.body, field)) values[field] = typeof req.body[field] === 'string' ? req.body[field].trim() : req.body[field]; return save(res, req.user.sub, values, 'profileCompletion', 'Profile details saved.'); } catch (error) { return next(error); } };
exports.photos = async (req, res, next) => { try { const profile = await getProfile(req.user.sub); const files = req.files || []; if (!files.length) return res.status(400).json({ success: false, message: 'Upload at least one photo.', code: 'VALIDATION_ERROR', errors: [{ field: 'photos', message: 'At least one photo is required.' }] }); if ((profile.photos || []).length + files.length > 6) { files.forEach((file) => remove(publicPath(file))); return res.status(400).json({ success: false, message: 'A maximum of 6 photos is allowed.', code: 'PHOTO_LIMIT_REACHED', errors: [{ field: 'photos', message: 'A maximum of 6 photos is allowed.' }] }); } profile.photos = [...(profile.photos || []), ...files.map(publicPath)]; advance(profile, 'photos'); await profile.save(); return success(res, 'Photos uploaded.', profile); } catch (error) { return next(error); } };
exports.deletePhoto = async (req, res, next) => { try { const profile = await getProfile(req.user.sub); const index = Number(req.params.index); const photos = [...(profile.photos || [])]; if (!Number.isInteger(index) || index < 0 || index >= photos.length) return res.status(400).json({ success: false, message: 'Photo index is invalid.', code: 'VALIDATION_ERROR', errors: [{ field: 'index', message: 'Photo index is invalid.' }] }); const [deleted] = photos.splice(index, 1); remove(deleted); profile.photos = photos; if (!photos.length) profile.primaryPhotoIndex = 0; else if (profile.primaryPhotoIndex === index) profile.primaryPhotoIndex = 0; else if (profile.primaryPhotoIndex > index) profile.primaryPhotoIndex -= 1; await profile.save(); return success(res, 'Photo removed.', profile); } catch (error) { return next(error); } };
exports.primaryPhoto = async (req, res, next) => { try { const profile = await getProfile(req.user.sub); const index = req.body.primaryPhotoIndex; if (index < 0 || index >= (profile.photos || []).length) return res.status(400).json({ success: false, message: 'Primary photo index is invalid.', code: 'VALIDATION_ERROR', errors: [{ field: 'primaryPhotoIndex', message: 'Primary photo index must reference an uploaded photo.' }] }); profile.primaryPhotoIndex = index; await profile.save(); return success(res, 'Primary photo updated.', profile); } catch (error) { return next(error); } };
exports.complete = async (req, res, next) => { try { const profile = await getProfile(req.user.sub); const missing = []; if (!profile.birthDate) missing.push('birthDate'); if (!profile.gender) missing.push('gender'); if (!(profile.interestedIn || []).length) missing.push('interestedIn'); if (!(profile.relationshipGoals || []).length) missing.push('relationshipGoals'); if (!profile.city) missing.push('city'); if ((profile.photos || []).length < 2) missing.push('photos'); if (missing.length) return res.status(400).json({ success: false, message: 'Complete all required onboarding fields before finishing.', code: 'ONBOARDING_INCOMPLETE', errors: missing.map((field) => ({ field, message: `${field} is required before completing onboarding.` })) }); profile.onboardingCompleted = true; profile.stage = 'complete'; await profile.save(); return success(res, 'Onboarding completed.', profile); } catch (error) { return next(error); } };
