const { getModels } = require('../models'); const { MAX_PROFILE_PHOTOS, store, publicPath, remove } = require('../utils/photoStorage');
const ranks = { age: 0, gender: 1, interestedIn: 2, relationshipGoal: 3, location: 4, starterProfile: 5, profileCompletion: 6, photos: 7, complete: 8 };
const success = (res, message, profile) => res.json({ success: true, message, data: { onboarding: profile.toJSON() } });
async function getProfile(userId, { transaction, lock } = {}) { const { OnboardingProfile } = getModels(); const [profile] = await OnboardingProfile.findOrCreate({ where: { userId }, defaults: { userId }, transaction, lock }); const photos = Array.isArray(profile.photos) ? profile.photos.filter((photo) => photo !== '[' && photo !== ']') : []; if (photos.length !== (profile.photos || []).length) { profile.photos = photos; profile.primaryPhotoIndex = Math.min(profile.primaryPhotoIndex, Math.max(0, photos.length - 1)); await profile.save({ transaction }); } return profile; }
function advance(profile, stage) { if (ranks[stage] > ranks[profile.stage]) profile.stage = stage; }
async function save(res, userId, values, stage, message) { const profile = await getProfile(userId); Object.assign(profile, values); advance(profile, stage); await profile.save(); return success(res, message, profile); }
exports.status = async (req, res, next) => { try { return success(res, 'Onboarding status retrieved.', await getProfile(req.user.sub)); } catch (error) { return next(error); } };
exports.age = async (req, res, next) => { try { return save(res, req.user.sub, { birthDate: req.body.birthDate }, 'age', 'Date of birth saved.'); } catch (error) { return next(error); } };
exports.gender = async (req, res, next) => { try { return save(res, req.user.sub, { gender: req.body.gender, customGender: req.body.gender === 'Other' ? (req.body.customGender || '').trim() : '' }, 'gender', 'Gender saved.'); } catch (error) { return next(error); } };
exports.interestedIn = async (req, res, next) => { try { return save(res, req.user.sub, { interestedIn: req.body.interestedIn }, 'interestedIn', 'Interested-in preferences saved.'); } catch (error) { return next(error); } };
exports.relationshipGoal = async (req, res, next) => { try { return save(res, req.user.sub, { relationshipGoals: req.body.relationshipGoals }, 'relationshipGoal', 'Relationship goals saved.'); } catch (error) { return next(error); } };
exports.location = async (req, res, next) => { try { const values = { city: req.body.city.trim() }; if (req.body.preferredDistance !== undefined) values.preferredDistance = req.body.preferredDistance; return save(res, req.user.sub, values, 'location', 'Location saved.'); } catch (error) { return next(error); } };
exports.starterProfile = async (req, res, next) => { try { const values = { profession: req.body.profession.trim(), education: req.body.education.trim() }; if (req.body.company !== undefined) values.company = req.body.company.trim(); return save(res, req.user.sub, values, 'starterProfile', 'Starter profile saved.'); } catch (error) { return next(error); } };
exports.profileCompletion = async (req, res, next) => { try { const fields = ['bio', 'interests', 'lifestyle', 'prompts', 'hometown', 'pronouns', 'sexuality', 'valuedQualities', 'loveLanguages', 'preferredTalkingHours', 'communicationStyle']; const values = {}; for (const field of fields) if (Object.prototype.hasOwnProperty.call(req.body, field)) values[field] = typeof req.body[field] === 'string' ? req.body[field].trim() : req.body[field]; return save(res, req.user.sub, values, 'profileCompletion', 'Profile details saved.'); } catch (error) { return next(error); } };
exports.photos = async (req, res, next) => { const stored = []; try { const files = req.files || []; if (!files.length) return res.status(400).json({ success: false, message: 'Upload at least one photo.', code: 'VALIDATION_ERROR', errors: [{ field: 'photos', message: 'At least one photo is required.' }] }); const { OnboardingProfile } = getModels(); let profile; await OnboardingProfile.sequelize.transaction(async (transaction) => { profile = await getProfile(req.user.sub, { transaction, lock: transaction.LOCK.UPDATE }); if ((profile.photos || []).length + files.length > MAX_PROFILE_PHOTOS) { const error = new Error(`A maximum of ${MAX_PROFILE_PHOTOS} photos is allowed.`); error.status = 400; error.code = 'PHOTO_LIMIT_REACHED'; throw error; } for (const file of files) stored.push(await store(req.user.sub, file)); profile.photos = [...(profile.photos || []), ...stored.map(publicPath)]; advance(profile, 'photos'); await profile.save({ transaction }); }); return success(res, 'Photos uploaded.', profile); } catch (error) { stored.forEach((filename) => remove(publicPath(filename))); if (error.code === 'PHOTO_LIMIT_REACHED') return res.status(400).json({ success: false, message: error.message, code: error.code, errors: [{ field: 'photos', message: error.message }] }); return next(error); } };
exports.deletePhoto = async (req, res, next) => { try { const { OnboardingProfile } = getModels(); const index = Number(req.params.index); let profile; let deleted; await OnboardingProfile.sequelize.transaction(async (transaction) => { profile = await getProfile(req.user.sub, { transaction, lock: transaction.LOCK.UPDATE }); const photos = [...(profile.photos || [])]; if (!Number.isInteger(index) || index < 0 || index >= photos.length) { const error = new Error('Photo index is invalid.'); error.status = 400; error.code = 'VALIDATION_ERROR'; throw error; } [deleted] = photos.splice(index, 1); profile.photos = photos; if (!photos.length) profile.primaryPhotoIndex = 0; else if (profile.primaryPhotoIndex === index) profile.primaryPhotoIndex = 0; else if (profile.primaryPhotoIndex > index) profile.primaryPhotoIndex -= 1; await profile.save({ transaction }); }); remove(deleted); return success(res, 'Photo removed.', profile); } catch (error) { if (error.code === 'VALIDATION_ERROR') return res.status(400).json({ success: false, message: error.message, code: error.code, errors: [{ field: 'index', message: error.message }] }); return next(error); } };
exports.primaryPhoto = async (req, res, next) => { try { const { OnboardingProfile } = getModels(); const index = req.body.primaryPhotoIndex; let profile; await OnboardingProfile.sequelize.transaction(async (transaction) => { profile = await getProfile(req.user.sub, { transaction, lock: transaction.LOCK.UPDATE }); if (index < 0 || index >= (profile.photos || []).length) { const error = new Error('Primary photo index must reference an uploaded photo.'); error.status = 400; error.code = 'VALIDATION_ERROR'; throw error; } profile.primaryPhotoIndex = index; await profile.save({ transaction }); }); return success(res, 'Primary photo updated.', profile); } catch (error) { if (error.code === 'VALIDATION_ERROR') return res.status(400).json({ success: false, message: 'Primary photo index is invalid.', code: error.code, errors: [{ field: 'primaryPhotoIndex', message: error.message }] }); return next(error); } };
exports.complete = async (req, res, next) => { try { const { OnboardingProfile } = getModels(); const result = await OnboardingProfile.sequelize.transaction(async (transaction) => { const profile = await getProfile(req.user.sub, { transaction, lock: transaction.LOCK.UPDATE }); const missing = []; if (!profile.birthDate) missing.push('birthDate'); if (!profile.gender) missing.push('gender'); if (!(profile.interestedIn || []).length) missing.push('interestedIn'); if (!(profile.relationshipGoals || []).length) missing.push('relationshipGoals'); if (!profile.city) missing.push('city'); if ((profile.photos || []).length < 2) missing.push('photos'); if (missing.length) return { profile, missing }; profile.onboardingCompleted = true; profile.stage = 'complete'; await profile.save({ transaction }); return { profile, missing }; }); if (result.missing.length) return res.status(400).json({ success: false, message: 'Profile completion failed.', code: 'ONBOARDING_INCOMPLETE', errors: result.missing.map((field) => ({ field, message: `${field} is required before completing onboarding.` })) }); return success(res, 'Onboarding completed.', result.profile); } catch (error) { return next(error); } };
