const r=require('express').Router();const {body,param,query}=require('express-validator');const v=require('../middleware/validateRequest');const {requireAdminPermission}=require('../middleware/adminRbacMiddleware');const c=require('../controllers/adminSafetyController');
const id=()=>param('reportId').isInt({min:1}).toInt();
r.get('/safety/reports',[query('page').optional().isInt({min:1}).toInt(),query('pageSize').optional().isInt({min:1,max:100}).toInt(),query('id').optional().isInt({min:1}).toInt(),query('reporterId').optional().isInt({min:1}).toInt(),query('reportedUserId').optional().isInt({min:1}).toInt(),query('assignedAdministratorId').optional().isInt({min:1}).toInt(),query('personalSearch').optional().isString().trim().isLength({min:1,max:160}),query('status').optional().isIn(['open','reviewing','resolved','dismissed']),query('caseStatus').optional().isIn(['open','under_review','action_required','resolved','dismissed']),query('severity').optional().isIn(['low','medium','high','critical']),query('reason').optional().isIn(['fake_profile','harassment','inappropriate_photo','scam','spam','other']),query('category').optional().isIn(['profile','event','message']),query('createdFrom').optional().isISO8601(),query('createdTo').optional().isISO8601(),query('resolvedFrom').optional().isISO8601(),query('resolvedTo').optional().isISO8601(),query('sortBy').optional().isIn(['reportId','createdAt','updatedAt','resolvedAt','severity']),query('sortDirection').optional().isIn(['asc','desc','ASC','DESC'])],v,requireAdminPermission('safety.reports.view'),c.list);
r.get('/safety/reports/:reportId',[id()],v,requireAdminPermission('safety.reports.details.view'),c.detail);
r.patch('/safety/reports/:reportId/assignment',[id(),body('administratorId').optional({nullable:true}).isInt({min:1}).toInt()],v,requireAdminPermission('safety.reports.assign'),c.assign);
r.post('/safety/reports/:reportId/notes',[id(),body('text').isString().trim().isLength({min:1,max:2000})],v,requireAdminPermission('safety.notes.manage'),c.note);
r.patch('/safety/reports/:reportId/status',[id(),body('status').isIn(['open','under_review','action_required','resolved','dismissed']),body('resolution').optional().isString().trim().isLength({max:2000})],v,requireAdminPermission('safety.cases.update'),c.status);
r.post('/safety/reports/:reportId/actions',[id(),body('action').isIn(['deactivate','reactivate']),body('reason').optional().isString().trim().isLength({max:500})],v,requireAdminPermission('safety.actions.suspend'),c.action);
module.exports=r;
