const express = require('express');
const { body } = require('express-validator');
const requireAuth = require('../middleware/authMiddleware');
const validateRequest = require('../middleware/validateRequest');
const controller = require('../controllers/boostController');
const { walletValueLimiter } = require('../middleware/rateLimiter');
const router = express.Router(); router.use(requireAuth);
router.get('/products', controller.products); router.get('/me', controller.me);
router.post('/purchase', walletValueLimiter, [body('productId').isString().trim().notEmpty(), body('source').optional().isIn(['wallet', 'provider']), body('idempotencyKey').optional().isString().isLength({ min: 8, max: 100 })], validateRequest, controller.purchase);
module.exports = router;
