const express = require('express'); const { body, query } = require('express-validator'); const controller = require('../controllers/discoverController'); const requireAuth = require('../middleware/authMiddleware'); const validateRequest = require('../middleware/validateRequest'); const { discoverSwipeLimiter } = require('../middleware/rateLimiter');
const { hasOnlyCommunicationStyles, parseCommunicationStyles } = require('../constants/communicationStyles');
const { DISCOVER_FILTER_RANGES } = require('../constants/discoverFilterRanges');
const router = express.Router(); const optionalInt = (name, min, max) => query(name).optional().isInt({ min, max }).withMessage(`${name} must be between ${min} and ${max}.`).toInt(); const optionalBodyInt = (name, min, max) => body(name).optional().isInt({ min, max }).withMessage(`${name} must be between ${min} and ${max}.`).toInt(); const optionalArray = (name) => body(name).optional().isArray().withMessage(`${name} must be an array.`);
const communicationStylesQuery = query('communicationStyles').optional().custom((value) => {
  if (!hasOnlyCommunicationStyles(value)) throw new Error('communicationStyles contains an invalid value.');
  return true;
}).customSanitizer((value) => parseCommunicationStyles(value));
const communicationStylesBody = body('communicationStyles').optional().custom((value) => {
  if (!Array.isArray(value) || !hasOnlyCommunicationStyles(value)) throw new Error('communicationStyles must be an array of approved values.');
  return true;
}).customSanitizer((value) => parseCommunicationStyles(value));
router.use(requireAuth);
const feedValidation = () => [optionalInt('page', 1, 100000), optionalInt('limit', 1, 30), optionalInt('minAge', DISCOVER_FILTER_RANGES.age.min, DISCOVER_FILTER_RANGES.age.max), optionalInt('maxAge', DISCOVER_FILTER_RANGES.age.min, DISCOVER_FILTER_RANGES.age.max), optionalInt('maxDistanceKm', DISCOVER_FILTER_RANGES.distanceKm.min, DISCOVER_FILTER_RANGES.distanceKm.max), optionalInt('minScore', DISCOVER_FILTER_RANGES.score.min, DISCOVER_FILTER_RANGES.score.max), communicationStylesQuery, query('verifiedOnly').optional().isBoolean().withMessage('verifiedOnly must be a boolean.'), query('onlineNow').optional().isBoolean().withMessage('onlineNow must be a boolean.'), query('hasEventInterest').optional().isBoolean().withMessage('hasEventInterest must be a boolean.'), query('reset').optional().isBoolean().withMessage('reset must be a boolean.'), query('surface').optional().isIn(['recommended', 'near_you', 'similar_interests', 'high_compatibility', 'new_here', 'recently_active']).withMessage('Invalid surface.')];
router.get('/feed', feedValidation(), validateRequest, controller.getFeed);
router.get('/ai-matches', feedValidation(), validateRequest, (req, _res, next) => { req.aiMatches = true; req.query.surface = 'high_compatibility'; next(); }, controller.getFeed);
router.post('/swipe', discoverSwipeLimiter, [body('targetUserId').isInt({ min: 1 }).withMessage('targetUserId must be a valid user id.').toInt(), body('action').isIn(['pass', 'like', 'superLike']).withMessage('action must be pass, like, or superLike.')], validateRequest, controller.swipe);
router.post('/rewind', controller.rewind);
router.get('/filters', controller.getFilters);
router.put('/filters', [optionalBodyInt('minAge', DISCOVER_FILTER_RANGES.age.min, DISCOVER_FILTER_RANGES.age.max), optionalBodyInt('maxAge', DISCOVER_FILTER_RANGES.age.min, DISCOVER_FILTER_RANGES.age.max), optionalBodyInt('maxDistanceKm', DISCOVER_FILTER_RANGES.distanceKm.min, DISCOVER_FILTER_RANGES.distanceKm.max), optionalBodyInt('minScore', DISCOVER_FILTER_RANGES.score.min, DISCOVER_FILTER_RANGES.score.max), body('city').optional().isString().trim(), body('minHeight').optional({ nullable: true }).isInt(DISCOVER_FILTER_RANGES.heightCm).withMessage(`minHeight must be between ${DISCOVER_FILTER_RANGES.heightCm.min} and ${DISCOVER_FILTER_RANGES.heightCm.max}.`).toInt(), optionalArray('hometown'), optionalArray('datingIntentions'), optionalArray('lifestyleTags'), body('education').optional().isString().trim(), body('profession').optional().isString().trim(), body('community').optional().isString().trim(), body('religion').optional().isString().trim(), optionalArray('languages'), optionalArray('pronouns'), body('sexuality').optional().isString().trim(), optionalArray('qualities'), optionalArray('preferredTalkingHours'), optionalArray('loveLanguages'), communicationStylesBody, body('smoking').optional().isString().trim(), body('drinking').optional().isString().trim(), body('weed').optional().isString().trim(), body('verifiedOnly').optional().isBoolean().withMessage('verifiedOnly must be a boolean.').toBoolean(), body('onlineNow').optional().isBoolean().withMessage('onlineNow must be a boolean.').toBoolean(), body('hasPrompts').optional().isBoolean().withMessage('hasPrompts must be a boolean.').toBoolean(), body('hasEventInterest').optional().isBoolean().withMessage('hasEventInterest must be a boolean.').toBoolean()], validateRequest, controller.updateFilters);
module.exports = router;
