const express = require('express');
const { body, query } = require('express-validator');
const requireAuth = require('../middleware/authMiddleware');
const validateRequest = require('../middleware/validateRequest');
const controller = require('../controllers/walletController');
const { walletValueLimiter } = require('../middleware/rateLimiter');
const router = express.Router(); router.use(requireAuth);
router.get('/', controller.get);
router.get('/products', [query('type').optional().isIn(['top_up', 'redemption'])], validateRequest, controller.products);
router.get('/transactions', [query('page').optional().isInt({ min: 1 }).toInt(), query('limit').optional().isInt({ min: 1, max: 50 }).toInt(), query('type').optional().isIn(['top_up', 'gift_spend', 'boost_spend', 'redemption', 'refund', 'adjustment'])], validateRequest, controller.transactions);
router.post('/redemptions', walletValueLimiter, [body('productId').isString().trim().notEmpty(), body('idempotencyKey').optional().isString().isLength({ min: 8, max: 100 })], validateRequest, controller.redeem);
router.post('/top-up/orders', walletValueLimiter, [body('productId').isString().trim().notEmpty(), body('idempotencyKey').optional().isString().isLength({ min: 8, max: 100 })], validateRequest, controller.topUpOrder);
module.exports = router;
