const ACCOUNT_DELETION_REASON_CODES = Object.freeze([
  'FOUND_SOMEONE',
  'TAKING_A_BREAK',
  'NOT_ENOUGH_MATCHES',
  'PRIVACY_CONCERNS',
  'TECHNICAL_ISSUES',
  'NO_LONGER_USE_APP',
  'OTHER',
]);

const ACCOUNT_DELETION_REASON_TEXT_MAX_LENGTH = 500;

module.exports = {
  ACCOUNT_DELETION_REASON_CODES,
  ACCOUNT_DELETION_REASON_TEXT_MAX_LENGTH,
};
